name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
   
   strategy:
    matrix:
      node-version: [14.17]

    steps:
      - name: Checkout
        uses: action/checkout@v3

      - name: Install and Build
        working-directory: ./angular_store
        run: npm install && npm run build && cp dist/angular_store/index.html dist/angular_store/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist/angular_store